apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent-conf
  namespace: vector
data:
  vector.toml: |2+

    data_dir                                = "/var/lib/vector"


    [api]
      enabled                               = true
      address                               = "127.0.0.1:8686"
      playground                            = true



    [sources.log_files]
      type                                  = "file"
      include                               = ["/var/log/pods/test_log-*/log-generator/*.log"]    
      read_from                             = "beginning"
      max_read_bytes                        = 8192

    [transforms.my_transform]
      type = "filter"
      inputs = ["log_files"]
      condition = '.kubernetes.pod_namespace == "test"'

    [sinks.kafka]
      type = "kafka"
      inputs = ["my_transform"]
      bootstrap_servers = "my-cluster-kafka-bootstrap.amq:9092"
      topic = "vector-topic"
      encoding.codec = "json"
